<?php
	define('INTEGER_LENGTH', 31); // Stupid signed bit for permissions

	$GLOBALS['PERM_DEFINES'] = array(
	'PERM_CS_ADMIN'=>array("title"=>'Can Access Admin Site', 'group'=>'General'),
	'PERM_PLUGIN_MANAGER'=>array("title"=>'Plugin Manager', 'group'=>'Plugins'),
	'PERM_PLUGIN_LANGUAGES'=>array("title"=>'Languages', 'group'=>'Plugins'),
	'PERM_PLUGIN_MEMBERS'=>array("title"=>'Members', 'group'=>'Plugins'),
	'PERM_PLUGIN_PAGE_EDITOR'=>array("title"=>'Page Editor', 'group'=>'Plugins'),
	'PERM_PLUGIN_STRING_EDITOR'=>array("title"=>'String Editor', 'group'=>'Plugins'),
	'PERM_PLUGIN_THEMES'=>array("title"=>'Themes', 'group'=>'Plugins'),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_HOLDER'=>array("title"=>'', 'group'=>''),
	'PERM_PLUGIN_ROLES'=>array("title"=>'Roles', 'group'=>'Plugins'),
	);
	
	// get the permission defines rolling
	$i=0;
	foreach ($GLOBALS['PERM_DEFINES'] as $perm=>$attribs)
	{
		define($perm, $i);
		$i++;
	}
	/*for ($i=0;$i<count($GLOBALS['PERM_DEFINES']);$i++)
	{
		define($GLOBALS['PERM_DEFINES'][$i], $i);//$bit->stringout());
	}*/		

?>
